service:
  name: ag-client-locator

plugins:
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    shouldStartNameWithService: true

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    timeout: 20
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true

custom:
  serverless-offline:
    noPrependStageInUrl: true
